name: ms-gen
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - rdkit
  - pytorch-lightning #1.7
  - einops
  - ipykernel
  - pytorch::pytorch #- dgl=0.7.*
  - mkl
  - nb_conda_kernels
  - seaborn
  - h5py
  - ray-tune
  - umap-learn
  - optuna
#  - cudatoolkit=11.1 # may need to modify if cpu only
  #- pytorch::torchvision
  #- torchmetrics
